<script type='text/javascript' src={{ asset('assets/js/vendor/jquery/jquery.min.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/vendor/jquery/jquery-migrate.min.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/custom/jquery.cookie.min.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/vendor/ui/core.min.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/vendor/ui/widget.min.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/vendor/ui/tabs.min.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/vendor/ui/effect.min.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/vendor/ui/effect-fade.min.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/custom/template.custom.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/custom/trx_utils.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/vendor/superfish/superfish.min.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/custom/template.utils.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/custom/template.init.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/custom/theme.init.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/custom/template.shortcodes.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/vendor/js_comp/js_comp.min.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/vendor/eventon/eventon_script.min.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/vendor/eventon/eventon_gen_maps.min.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/vendor/cform/jquery.form.min.js') }}></script>
<script type='text/javascript' src={{ asset('assets/js/vendor/cform/scripts.min.js') }}></script>
